stages:
  - lint
  - preproc

.python-setup:
  image: python:3.8
  before_script:
    - pip install --upgrade pip setuptools wheel
    - pip install -r requirements.txt

.lint:
  extends: .python-setup
  stage: lint

.preproc:
  extends: .python-setup
  stage: preproc
  artifacts:
    - outputs/

.visualizations:
  extends: .python-setup
  stage: visualizations
  artifacts:
    - outputs/

black:
  extends: .lint
  script:
    - make check-black

isort:
  extends: .lint
  script:
    - make check-isort

pylint:
  extends: .lint
  script:
    - make check-pylint

mypy:
  extends: .lint
  script:
    - make check-mypy

parse_ideb:
  extends: .preproc
  script:
    - make parse_ideb

homicides_per_capita:
  extends: .preproc
  script:
    - make homicides_per_capita

correlate:
  extends: .visualizations
  script:
    - make correlate

population_trend:
  extends: .visualizations
  script:
    - make population_trend
