[tool.black]
line-length = 80
target-version = ["py38"]

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 80
src_paths = ["src" , "scripts"]

[tool.mypy]
namespace_packages = true
explicit_package_bases = true
warn_unused_configs = true

# mypy per-module options:

[[tool.mypy.overrides]]
module = [
    "matplotlib.*",
    "scipy.*",
    "sklearn.*",
    "pandas",
]
ignore_missing_imports = true

[tool.pylint.master]
init-hook = "from pylint.config import find_default_config_files; import os, sys; sys.path.append(os.path.dirname(list(find_default_config_files())[0]))"

[tool.pylint.messages_control]
disable = [
    "R0914",  # too-many-local-variables
]

[tool.pylint.basic]
good-names = [
    "i",
    "j",
    "x",
    "y",
    "X",
    "k",
    "ax",
    "_",
]
