"""Project-wide constants."""

# Assets filenames

# All files were obtained from:
# https://www.gov.br/inep/pt-br/areas-de-atuacao/pesquisas-estatisticas-e-indicadores/ideb/resultados
IDEB_SCHOOL_FILENAME_FORMAT = "divulgacao_{}_municipios_2019.ods"

# Initial data obtained from https://www.todamateria.com.br/capitais-do-brasil/,
# and sorted by state abbreviation. We also inserted the county codes from the
# homicides spreadsheet in the first column of this one.
BRAZILIAN_CAPITALS_FILENAME = "capitais_brasil.csv"

# Obtained from http://www.ipeadata.gov.br/Default.aspx by navigating through
# the menus regional > Temas > Segurança Pública and selecting
# "Número de homicídios" in capitals with the largest possible range.
HOMICIDES_PER_CAPITAL_FILENAME = "homicidios_capitais_ipea.csv"

# Obtained by combining the following sources:
# 1. https://censo2010.ibge.gov.br/sinopse/index.php?dados=6
# 2. https://pt.wikipedia.org/wiki/Lista_de_capitais_do_Brasil_por_popula%C3%A7%C3%A3o
POPULATION_PER_CAPITAL_FILENAME = "populacao_capitais_ibge.csv"


# Outputs filenames

# File generated by module sripts.homicides_per_capita
HOMICIDES_PER_CAPITA_PER_CAPITAL_FILENAME = "homicides_per_capita.pkl"

# File generated by module sripts.parse_ideb
IDEB_CAPITALS_FILENAME_FORMAT = "ideb_capitals_{}_{}.csv"
